// Produces the submission evidence: both tasks on both drivers (each with a measured baseline run),
// the ship step, standards reports and the extensibility simulation, then an index in reports/EVIDENCE.md.
// Without provider keys it uses the offline wire-level provider and says so in every artifact.
import { spawnSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { graderSim } from './grader-sim.ts';
import { offlineRun } from './offline-run.ts';
import type { RunReport } from '../src/core/engine.ts';
import { REPO_ROOT, writeText } from '../src/core/util.ts';

const live = (process.env['ANTHROPIC_API_KEY'] ?? '') !== '' && (process.env['OPENAI_API_KEY'] ?? '') !== '' && process.argv.includes('--live');
const rows: string[] = [];
const notes: string[] = [];

async function run(task: string, driver: string): Promise<void> {
  const args = ['--task', task, '--driver', driver, '--with-baseline'];
  let output: string;
  if (live) {
    const r = spawnSync(process.execPath, ['src/core/cli.ts', 'run', ...args], { cwd: REPO_ROOT, encoding: 'utf8' });
    output = `${r.stdout}${r.stderr}`;
    process.stdout.write(output);
  } else output = (await offlineRun(args)).output;
  const reports = [...output.matchAll(/report\s+(reports\/\S+\.json)/g)].map((m) => m[1] ?? '');
  const actualPath = reports.at(-1);
  if (actualPath === undefined) {
    rows.push(`| ${task} | ${driver} | ERROR (no report) | | | | |`);
    return;
  }
  const r = JSON.parse(readFileSync(join(REPO_ROOT, actualPath), 'utf8')) as RunReport;
  const t = JSON.parse(readFileSync(join(REPO_ROOT, r.paths.tokens), 'utf8')) as { reductionPercent: number; reductionVsMeasuredBaselinePercent?: number };
  rows.push(
    `| ${r.task} | ${r.driver} | ${r.verdict.toUpperCase()} | ${r.turns} | ${t.reductionPercent}% / ${String(t.reductionVsMeasuredBaselinePercent ?? 'n/a')}% | ${r.ship?.status ?? '-'} \`${r.ship?.branch ?? ''}\` ${r.ship?.commit?.slice(0, 10) ?? ''} | [report](../${r.paths.report}) · [tokens](../${r.paths.tokens}) · [logs](../${r.paths.logs}) |`,
  );
  if (r.ship?.pullRequest !== undefined) notes.push(`- ${r.task} / ${r.driver}: PR ${r.ship.pullRequest}${r.ship.reason !== undefined ? ` (${r.ship.reason})` : ''}`);
}

for (const task of ['tasks/users-api.json', 'tasks/orders-cancel.json']) {
  for (const driver of ['claude', 'openai']) await run(task, driver);
}

const sim = graderSim();
writeText(join(REPO_ROOT, 'reports', 'grader-sim.txt'), `${sim.log}\n`);

const index = `# Run evidence

Generated by \`npm run evidence\` on ${new Date().toISOString()}.

**Provider mode: ${live ? 'LIVE provider APIs' : 'OFFLINE wire-level provider (no API keys were available)'}.**
${live ? '' : `Both drivers ran unmodified against a local server that validates and answers the real Anthropic Messages and
OpenAI Chat Completions wire formats (test/fake-provider/). The model behind it is a scripted stand-in, so these runs prove
the harness, the drivers' translation and the gates, and are **UNPROVEN** for live model behaviour.`}

| task | driver | verdict | turns | input-token reduction (shadow / measured baseline) | ship | evidence |
|---|---|---|---|---|---|---|
${rows.join('\n')}

Pull requests:
${notes.join('\n')}

Extensibility simulation: **${sim.ok ? 'PASS' : 'FAIL'}** → [grader-sim.txt](grader-sim.txt)
`;
writeText(join(REPO_ROOT, 'reports', 'EVIDENCE.md'), index);
process.stdout.write(`\n${index}`);
